binance_1m = """CREATE TABLE kline_1m (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_5m = """CREATE TABLE kline_5m (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_15m = """CREATE TABLE kline_15m (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_30m = """CREATE TABLE kline_30m (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_1h = """CREATE TABLE kline_1h (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_2h = """CREATE TABLE kline_2h (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_4h = """CREATE TABLE kline_4h (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_8h = """CREATE TABLE kline_8h (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_1d = """CREATE TABLE kline_1d (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_1w = """CREATE TABLE kline_1w (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

binance_1mo = """CREATE TABLE kline_1mo (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(100),
    open_price DECIMAL(18, 8),
    close_price DECIMAL(18, 8),
    high_price DECIMAL(18, 8),
    low_price DECIMAL(18, 8),
    open_time BIGINT,
    close_time BIGINT,
    quote_asset_volume DECIMAL(18, 8),
    number_of_trades INT,
    taker_buy_asset_volume DECIMAL(18, 8),
    taker_buy_quote_asset_volume DECIMAL(18, 8),
    price_change DECIMAL(18, 8),
    price_change_percent DECIMAL(18, 8),
    weighted_avg_price DECIMAL(18, 8),
    prev_close_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    volume DECIMAL(18, 8),
    first_id BIGINT,
    last_id BIGINT,
    trade_count INT
);
"""

klines = [
    binance_1m,
    binance_5m,
    binance_15m,
    binance_30m,
    binance_1h,
    binance_2h,
    binance_4h,
    binance_8h,
    binance_1d,
    binance_1w,
    binance_1mo
]